services:
  - type: web
    name: stage290
    runtime: python
    repo: https://github.com/mokkunsuzuki-code/stage290
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
